/// Every `generate_handler!` command in `src/lib.rs`, in the same order. With an
/// app ACL manifest Tauri admits a command only from a window whose capability
/// grants it; `verify:shell-contracts` fails when this list and the handler list
/// differ. tauri-build writes one file per entry into `permissions/autogenerated/`,
/// which is committed on purpose. docs/architecture/ui-and-shell.md, "Capabilities".
const APP_COMMANDS: &[&str] = &[
    "update_tray_labels",
    "list_serial_ports",
    "connect_serial_port",
    "get_serial_connection_status",
    "run_serial_health_check",
    "discover_hue_bridges",
    "verify_hue_bridge_ip",
    "pair_hue_bridge",
    "validate_hue_credentials",
    "migrate_hue_credentials",
    "list_hue_entertainment_areas",
    "check_hue_stream_readiness",
    "start_hue_stream",
    "stop_hue_stream",
    "restart_hue_stream",
    "set_hue_solid_color",
    "get_hue_stream_status",
    "get_hue_area_channels",
    "set_lighting_mode",
    "stop_lighting",
    "get_lighting_mode_status",
    "get_runtime_telemetry",
    "show_notification",
    "request_notification_permission",
    "open_log_dir",
    "get_screen_capture_permission",
    "open_screen_capture_settings",
    "list_displays",
    "open_display_overlay",
    "close_display_overlay",
    "update_display_overlay_preview",
    "copy_background_image",
    "update_hue_channel_positions",
    "create_hue_zone",
    "update_hue_zone",
    "delete_hue_zone",
    "assign_channel_to_hue_zone",
    "simulate_hue_fault",
    "discover_wled_devices",
    "connect_wled_sink",
    "test_wled_bridge",
    "get_wled_sink_status",
    "start_led_test_pattern",
    "stop_led_test_pattern",
    "get_led_preview_status",
    "open_led_twin_overlay",
    "close_led_twin_overlay",
    "open_led_control_popup",
    "show_led_control_popup",
    "hide_led_control_popup",
    "check_for_update",
    "download_and_install_update",
    "get_launch_context",
    "get_shell_state",
    "patch_shell_state",
    "replace_shell_state",
    "apply_outputs",
    "retune_lighting",
    "release_hue_output",
    "get_lighting_runtime",
];

fn main() {
    // tauri-build embeds the app manifest as a bin-only resource, so test binaries
    // get none and die at load on comctl32 v6 imports (STATUS_ENTRYPOINT_NOT_FOUND).
    // Embedding it ourselves below covers every linked target with one manifest.
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest())
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run tauri-build");

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows")
        && std::env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc")
    {
        let manifest = std::path::Path::new(&std::env::var("CARGO_MANIFEST_DIR").unwrap())
            .join("windows-app-manifest.xml");
        println!("cargo:rerun-if-changed={}", manifest.display());
        println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
        println!("cargo:rustc-link-arg=/MANIFESTINPUT:{}", manifest.display());
    }

    // On macOS, add Swift stdlib rpath so screencapturekit can find
    // libswift_Concurrency.dylib at runtime.
    //
    // Prefer the OS-embedded path (/usr/lib/swift) which is already in the
    // dyld cache on macOS 12+. Using the Xcode toolchain copy causes duplicate
    // class registration warnings because the OS also loads the cache version.
    #[cfg(target_os = "macos")]
    {
        // /usr/lib/swift is the canonical OS location on macOS 12+ and the file
        // exists there as a regular dylib (not only in the dyld cache).
        let system_swift = "/usr/lib/swift";
        if std::path::Path::new(system_swift)
            .join("libswift_Concurrency.dylib")
            .exists()
        {
            println!("cargo:rustc-link-arg=-Wl,-rpath,{}", system_swift);
        } else {
            // Fallback: find Xcode toolchain Swift-5.5 macosx libs via xcrun.
            if let Some(path) = xcode_swift_macosx_lib_path() {
                println!("cargo:rustc-link-arg=-Wl,-rpath,{}", path);
            }
        }
    }
}

#[cfg(target_os = "macos")]
fn xcode_swift_macosx_lib_path() -> Option<String> {
    let output = std::process::Command::new("xcrun")
        .args(["--find", "swiftc"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let swiftc = String::from_utf8(output.stdout).ok()?;
    let toolchain_usr = std::path::Path::new(swiftc.trim())
        .parent()? // bin
        .parent()?; // usr
    let candidate = toolchain_usr.join("lib/swift-5.5/macosx");
    if candidate.exists() {
        return Some(candidate.to_string_lossy().into_owned());
    }
    None
}
